version: '3.8'

services:
  espumdesk_app:
    build:
      context: .
      dockerfile: .deploy/Dockerfile
    container_name: espumdesk_app
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
    volumes:
      - .:/var/www/html
      - espumdesk-public:/var/www/html/public     # ✅ Volumen dedicado y externo
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_PORT}"
    depends_on:
      - espumdesk_db
      - espumdesk_redis
    networks:
      - proxy_net

  espumdesk_db:
    image: mysql:8.0
    container_name: espumdesk_db
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - espumdesk_db_data:/var/lib/mysql
    networks:
      - proxy_net

  espumdesk_redis:
    image: redis:7-alpine
    container_name: espumdesk_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

volumes:
  espumdesk_db_data:
  espumdesk-public:
    external: true
    name: espumdesk-public
